# Questo file viene utilizzato per eseguire i contenitori Docker per il progetto Django

version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
