# Generated by Django 4.2.7 on 2023-11-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='FoodApp.ingredient'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='recipes',
            field=models.ManyToManyField(related_name='restaurants', to='FoodApp.recipe'),
        ),
    ]
